spring.application.name=JAVA
server.port = 8888

openai.api.key = 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